export { default as LeftArrowBold } from "./img/LeftArrowBold.png";
export { default as RightArrowBold } from "./img/RightArrowBold.png";
export { default as DAELogo } from "./img/DAEDAE.png";
export { default as DAEDAE } from "./img/daedaedae.png";
export { default as ProfileNone } from "./img/Profile.png";
export { default as Edit } from "./img/Edit.png";
export { default as DownArrow } from "./img/DownArrow.png";
export { default as Close } from "./img/Close.png";
export { default as Link } from "./img/Link.png";
